# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: r0n1n
title: Open Source Contributor
email: gitr0n1n@protonmail.com
website: www.github.com/gitr0n1n

# Social links
twitter_username: longsats
github_username:  gitr0n1n
discord_username: r0n1n
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About r0n1n
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's r0n1n and I'm an open source contributor. As well as contributing to open srouce projects I also have experience in accounting and finance. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>GAAP Accounting</mark> and <mark>Financial Management</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in cryptocurrency and fintech software some of my other interests and hobbies are:
   - Regneratice Agriculture
   - Algorithmic Trading Systems
   - Mountain Sports
   - Cryptocurrency Exchange Software

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
